Repository mediacloud/web-search, pull requests merged in 2023-02, with the labels that each got.

#274 Refactored authSlice.js
  mcweb/frontend/src/features/auth/authSlice.js
  mcweb/frontend/src/features/search/query/SelectedMedia.jsx
Labels: bug, low

#271 Edit upload source csv method
  mcweb/backend/sources/api.py
  mcweb/backend/sources/models.py
  mcweb/backend/sources/serializer.py
  mcweb/frontend/src/app/services/collectionsApi.js
  mcweb/frontend/src/app/services/sourceApi.js
  mcweb/frontend/src/app/store.js
  requirements.txt
Labels: bug, enhancement, directory

#276 Update release
  mcweb/backend/search/views.py
  mcweb/frontend/static/about/release_history.json
  mcweb/settings.py
Labels: bug, enhancement, search, directory

#278 RE: Hide Stories on a source page if it is not online_news
  mcweb/frontend/src/features/sources/SourceShow.jsx
Labels: bug, directory
