Repository mediacloud/web-search, pull requests merged in 2023-03, with the labels that each got.

#286 RE: Add message when total attention returns 0 or 100%
  mcweb/frontend/src/features/search/results/TotalAttentionResults.jsx
Labels: enhancement, search

#291 Feature rescrape UI Additions
  mcweb/backend/sources/api.py
  mcweb/backend/sources/serializer.py
  mcweb/frontend/src/app/services/sourceApi.js
  mcweb/frontend/src/features/sources/SourceHeader.jsx
Labels: enhancement, directory

#293 Temporarily shut off source name validations
  mcweb/backend/sources/serializer.py
  mcweb/frontend/src/features/feeds/FeedStories.jsx
Labels: bug, directory

#294 Feature task UI
  mcweb/frontend/src/app/services/sourceApi.js
  mcweb/frontend/src/features/auth/Account.jsx
  mcweb/frontend/src/features/tasks/TaskList.jsx
Labels: enhancement, directory

#296 Add rescrape of source when uploading a new source
  mcweb/backend/sources/api.py
  mcweb/frontend/src/features/collections/ModifyCollection.jsx
  mcweb/frontend/src/features/sources/UploadSources.jsx
Labels: enhancement, directory
