Repository mediacloud/web-search, pull requests merged in 2024-10, with the labels that each got.

#810 Feature add static collections
  mcweb/backend/sources/migrations/0024_collection_static.py
  mcweb/backend/sources/models.py
  mcweb/backend/sources/serializer.py
  mcweb/frontend/src/features/collections/CollectionHeader.jsx
  mcweb/frontend/src/features/collections/ModifyCollection.jsx
  mcweb/frontend/src/features/sources/SourceList.jsx
  mcweb/frontend/src/features/sources/UploadSources.jsx
Labels: enhancement, directory

#819 Change static to managed for collections
  mcweb/backend/sources/api.py
  mcweb/backend/sources/migrations/0025_rename_static_collection_managed.py
  mcweb/backend/sources/models.py
  mcweb/backend/sources/serializer.py
  mcweb/frontend/src/features/collections/CollectionHeader.jsx
  mcweb/frontend/src/features/collections/CreateCollection.jsx
  mcweb/frontend/src/features/collections/ModifyCollection.jsx
Labels: bug, enhancement, directory

#825 Update version and release notes for new release
  mcweb/frontend/static/about/release_history.json
  mcweb/settings.py
Labels: documentation, enhancement

#824 Feature add contributor roles
  doc/management-commands.md
  mcweb/backend/users/management/commands/create-groups.py
  mcweb/backend/users/views.py
  mcweb/frontend/src/features/auth/Account.jsx
  mcweb/frontend/src/features/auth/Permissioned.jsx
  mcweb/frontend/src/features/collections/CollectionHeader.jsx
  mcweb/frontend/src/features/collections/ModifyCollection.jsx
  mcweb/frontend/src/features/directory/DirectoryHome.jsx
  mcweb/frontend/src/features/feeds/FeedHeader.jsx
  mcweb/frontend/src/features/header/Header.jsx
  mcweb/frontend/src/features/sources/ListSourceFeeds.jsx
  mcweb/frontend/src/features/sources/SourceHeader.jsx
  mcweb/frontend/src/features/sources/UploadSources.jsx
Labels: documentation, enhancement, search, directory

#834 Updated footer layout and fixed links
  .gitignore
  mcweb/backend/sources/migrations/0024_alter_source_alerted.py
  mcweb/backend/sources/migrations/0025_alter_collection_featured.py
  mcweb/backend/sources/migrations/0026_alter_collection_public.py
  mcweb/frontend/src/features/footer/Footer.jsx
Labels: enhancement

#835 Update backend permissions for contributors
  mcweb/backend/sources/api.py
  mcweb/backend/sources/permissions.py
  mcweb/backend/users/views.py
Labels: bug

#836 Fix bug where bar would not show with one result
  mcweb/frontend/src/features/search/results/BarChart.jsx
  mcweb/frontend/src/features/search/results/TopLanguages.jsx
  mcweb/frontend/src/features/search/results/TopSources.jsx
Labels: bug, search

#838 Bump version and add release notes for release
  mcweb/frontend/static/about/release_history.json
  mcweb/settings.py
Labels: documentation

#840 Move top words to bottom of results components
  mcweb/frontend/src/features/search/TabbedSearch.jsx
Labels: search
