Repository mediacloud/web-search, pull requests merged in 2024-11, with the labels that each got.

#849 Fix MC story page
  mcweb/backend/search/views.py
  mcweb/backend/sources/migrations/0024_alter_source_alerted.py
  mcweb/backend/sources/migrations/0025_alter_collection_featured.py
  mcweb/backend/sources/migrations/0026_alter_collection_public.py
  mcweb/frontend/src/features/auth/Permissioned.jsx
  mcweb/frontend/src/features/search/results/SampleStoryShow.jsx
  mcweb/frontend/src/features/stories/StoryShow.jsx
  mcweb/frontend/src/features/ui/InfoMenu.jsx
Labels: bug, search, directory

#850 Fix migrations
  mcweb/frontend/src/features/collections/CollectionShow.jsx
  mcweb/frontend/src/features/collections/FeaturedCollections.jsx
Labels: bug

#856 quota.check method, invocation /before/ expensive backend calls to raise quota errors in a more useful way
  mcweb/backend/search/views.py
  mcweb/backend/users/models.py
Labels: bug, enhancement, search

#859 Change weekly quota to 4k
  mcweb/backend/users/migrations/0014_alter_profile_quota_mediacloud_and_more.py
  mcweb/backend/users/models.py
Labels: bug, enhancement, search

#864 Fix #795: Improve notes field rendering as Markdown
  mcweb/frontend/src/features/collections/CollectionShow.jsx
  mcweb/frontend/src/features/collections/FeaturedCollections.jsx
  mcweb/frontend/src/features/collections/util/formatNotesToHTML.jsx
  mcweb/frontend/src/features/sources/SourceShow.jsx
Labels: enhancement, directory

#863 Update 'Compare Across the Globe' to Focus on English-Speaking Countries and Add (EN) Label
  mcweb/frontend/src/features/search/util/generateComparativeQuery.js
  mcweb/frontend/src/features/ui/TabDropDownMenu.jsx
Labels: enhancement, search

#865 Update version and release notes for new release
  mcweb/frontend/static/about/release_history.json
  mcweb/settings.py
Labels: documentation, search, directory
