Repository mediacloud/web-search, pull requests merged in 2025-03, with the labels that each got.

#965 Chore/sources update language pub date
  mcweb/backend/sources/management/commands/sources-meta-update.py
  mcweb/backend/sources/tasks.py
Labels: directory

#1028 Update release notes and re-add static files
  mcweb/frontend/src/features/about/ReleaseNotes.jsx
  mcweb/frontend/src/features/about/release_history.json
  mcweb/static/img/attention_over_time_annotated.jpg
  mcweb/static/img/compare-partisanship.png
  mcweb/static/img/fail-fox-bad-url.png
  mcweb/static/img/favicon.ico
  mcweb/static/img/media_picker_modal.jpg
  mcweb/static/img/mediacloud-logo-white-2x.png
  mcweb/static/img/query-screen.png
  mcweb/static/img/screenshot-attention-over-time.png
  mcweb/static/img/top_words.jpg
  mcweb/static/img/total-attention-global.png
Labels: bug, documentation

#1034 Add frontend checks to ensure data is available
  mcweb/frontend/src/features/search/results/CountOverTimeResults.jsx
  mcweb/frontend/src/features/search/results/TopLanguages.jsx
  mcweb/frontend/src/features/search/results/TopSources.jsx
  mcweb/frontend/src/features/search/results/TotalAttentionResults.jsx
  mcweb/frontend/src/features/search/util/getColors.js
  mcweb/frontend/src/features/search/util/prepareCountOverTimeData.js
  mcweb/frontend/src/features/search/util/prepareLanguageData.js
  mcweb/frontend/src/features/search/util/prepareSourcesData.js
  mcweb/frontend/src/features/search/util/prepareTotalAttentionData.js
Labels: bug, search

#1041 Minor directory updates
  mcweb/backend/sources/data/featured-collections.json
  mcweb/backend/sources/serializer.py
  mcweb/frontend/src/features/collections/CollectionShow.jsx
  mcweb/frontend/src/features/collections/CreateCollection.jsx
  mcweb/frontend/src/features/sources/SourceHeader.jsx
  mcweb/frontend/src/features/sources/SourceShow.jsx
Labels: bug, enhancement, directory

#1040 Update reset behavior
  mcweb/backend/users/api.py
  mcweb/backend/users/management/commands/create-groups.py
  mcweb/backend/users/migrations/0016_resetcodes.py
  mcweb/backend/users/models.py
  mcweb/backend/users/serializer.py
  mcweb/backend/users/urls.py
  mcweb/backend/users/views.py
  mcweb/frontend/src/App.jsx
  mcweb/frontend/src/app/services/authApi.js
  mcweb/frontend/src/features/auth/Account.jsx
  mcweb/frontend/src/features/auth/ConfirmedReset.jsx
  mcweb/frontend/src/features/auth/GetApiAccess.jsx
  mcweb/frontend/src/features/auth/Permissioned.jsx
  mcweb/frontend/src/features/auth/ResetPassword.jsx
  mcweb/frontend/src/features/search/TabbedSearch.jsx
Labels: bug, enhancement, api
